# Site settings
author: Kimfucious
baseurl: "/Colin_Blog"
brand: Some words
copyright: Colin
description: A clean Jekyll theme with baked in Bootstrap 4, responsive images, and more...
email: example@example.com 
title: Sakura Jekyll Theme 
url: "https://colawithrain.github.io"

# Not using because Gulp is now processing SCSS
# sass:
#   sass_dir: css
#   style: compressed

# Algolia Search
algolia:
  application_id: 4P42FOBOZA # Use your (non-admin) search only api key here.
  index_name: sakura #Use an index you created on Algolia.

# Collections
collections:
  docs:
    output: true
    # permalink: ""
    permalink: "/:collection/:path/"
  posts:
    output: true
    permalink: "/:collection/:title/"

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post 
      type: post
  - scope:
      path: "pages"
      type: pages
    values:
      layout: default 
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: post
      type: doc

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "publish.sh",
  "yarn-error.log",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "Colin_Blog/page:num"
  sort_reverse: true
  title: ":title"
  trail:
    before: 2
    after: 2

# Plugins
plugins: [jekyll-paginate, jemoji, jekyll-sitemap, jekyll-seo-tag]
# 找到原因了，因为本地运行的时候v2还在，主动调用了v2的组件，但是gh上面自动不运行v2，所以出不来paginator

# SEO
social:
  name: Kimfucious
  links:
    - https://github.com/kimfucious
    - https://www.linkedin.com/in/kimaford/
webmaster_verifications:
  google: uubLfpcORmDWkM8pI-yKODVVZD3VSpUYFSwkQJcOuZE


# Social icons
show_social_icons: true
facebook_username: 
github_username: kimfucious 
googleplus_username: 
linkedin_username: kimaford
slack_username: 
twitter_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM